### ISSUE TITLE
Can't update this Collection

### ISSUE THREAD

**Issue by philipptempel** [sto3014/LRPhotos#1]
Hi,

Just downloaded your plugin, installed it according to the installation guides, and then set up a new "Photos" publish service. On my first export, I received the error

"Can’t update this collection.
An internal error has occurred: PhotosPublishTask.lua:35: bad argument #1 to 'find' (string expected, got nil)"

<img width="260" alt="Screen Shot 2022-01-13 at 3 49 05 PM" src="https://user-images.githubusercontent.com/1541337/149352271-6197669d-b8c9-4e9c-ac3c-e887583df608.png">

Only configuration I changed was unchecking "Include Video Files". But even with the option checked, it still fails.
Tried with Photos.app open and closed. Neither being successful.

System Information:
macOS 11.6.2 Big Sur.
Adobe Lightroom Classic 11.1 Release
Adobe Camera Raw 14.1

**Comment by sto3014** [comment]
Hello Philipp,

my fault, I guess.
I did not provide a reasonable error message.

Please take look at your public service settings.
If I’m not wrong, „Use one album for all collections“ is checked, but there is no value provided.
In the figure below I provided the album name "/2021/From Lightroom“. I.e. „From Lightroom“ will be the album in Photos and /2021 is the folder for the album.




Can you please check this? 


Regards
Dieter

**Comment by sto3014** [comment]
Hi Philipp,

my screenshot was not included in my response:
<img width="610" alt="image" src="https://user-images.githubusercontent.com/57503531/149419379-2ef76e46-1887-4687-b08f-0dfe54121218.png">

**Comment by sto3014** [comment]
Hi Philipp,

I just released [1.0.0.2 ](https://github.com/sto3014/LRPhotos/archive/refs/tags/1.0.0.2.zip).
There was an additional bug with the album name. Now it should be fixed.
Regards
Dieter

**Comment by sto3014** [comment]
Hi Philipp,

by the way: you may leave the album name empty. If you do so, the photos are imported but no album is used.
In 10.0.0.1 this behavior was intended but because of bug you became an error message.
10.0.0.2 should work as expected.
Regards
Dieter

**Comment by philipptempel** [comment]
Thanks for all the responses, Dieter.

I did have a value set for the album name: the default as given when installing the plugin i.e., `/Lightroom/Import`.
After unchecking the option to `Use Album` option, exporting worked (sort of).

Another error I encountered was that checking `Include Video Files` and exporting unsupported video formats (with the `Video Format` set to `Original, unedited file`. In my case I have some old `*.WMV` I wanted to port to Photos.app, which just gives me the plain error `Error while importing photos`.

<img width="260" alt="Screen Shot 2022-01-14 at 10 07 10 AM" src="https://user-images.githubusercontent.com/1541337/149489109-29089e59-1997-4205-841c-82dc3a109eea.png">

For what it's worth, I did not have any folder/album called `/Lightroom/Import` in my Photos.app before exporting. But even after creating the folder/album, I am still getting the same error message as in my original report.

<img width="243" alt="Screen Shot 2022-01-14 at 10 09 16 AM" src="https://user-images.githubusercontent.com/1541337/149489437-92edea9e-e0a6-404f-aae0-7d9bedfccf3e.png">

I will now try `v1.0.0.2` and report back if the problem still occurs.

**Comment by philipptempel** [comment]
With `v1.0.0.2`, everything seems to be working fine now. Tried

* [x] exporting without an album ` `: worked
* [x] exporting with an album `/Lightroom`: worked
* [x] exporting with a folder and album `/Lightroom/Import`: worked

Even without having to first create the folder/album in Photos.app.

For now, the issue can be marked as resolved for my use case. Have not chosen the other album options `Use collection name as album` nor `Ignore Albums by Regex` cause they don't fit to my use case (yet). But maybe down the line I will have to reopen as I am now just getting started in moving my library from Lightroom to Photos.app
